services:
 
  # Backend (NestJS)
  backend:
    image: node:18-alpine
    container_name: filmtdf_backend
    working_dir: /app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app  
    command: npm run start:dev
    ports:
      - "3000:3000"
    
#  Frontend (Next.js)
  frontend:
    image: node:20-alpine
    container_name: filmtdf_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--max-old-space-size=4096
    
    command: npm run dev -- --webpack
    ports:
      - "3001:3000" 

volumes:
  postgres_data: